<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now()->format('Y-m-d H:i:s');

        DB::table('employees')->insert([
            [
                'name' => 'Valdinei',
                'surname' => 'dos Santos Nascimento',
                'salary' => null,
                'agreement' => 0,
                'contacts' => json_encode(['+5573988559571', '+5573988121072']),
                'function_name' => 'CEO',
                'transportation_voucher' => false,
                'payment_method_id' => null,
                'overtime_payment_method_id' => null,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Samuel',
                'surname' => 'Correia Nascimento',
                'salary' => 2500,
                'agreement' => 0,
                'contacts' => json_encode(['+5573988121518']),
                'function_name' => 'Técnico em Informática',
                'transportation_voucher' => false,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => 4,
                'pix_cpf' => '06489734508',
                'pix_email' => 'samuca.7cn@gmail.com',
                'pix_phone_number' => '73988121518',
                'pix_token' => null,
                'bank_ag' => '00701',
                'account_type_id' => 1,
                'account_number' => '689785',
                'fired' => false,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Maria Aparecida',
                'surname' => 'Santos',
                'salary' => 2824,
                'agreement' => 0,
                'contacts' => json_encode(['+5573981061797']),
                'function_name' => 'Gerente Administrativo',
                'transportation_voucher' => true,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73981061797',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2020-01-02 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Marcos',
                'surname' => 'dos Santos Nascimento',
                'salary' => 2864.4,
                'agreement' => 0,
                'contacts' => json_encode(['+5582988079061']),
                'function_name' => 'Caldeireiro',
                'transportation_voucher' => false,
                'payment_method_id' => 2,
                'overtime_payment_method_id' => 4,
                'bank_id' => null,
                'pix_cpf' => '98779451500',
                'pix_email' => null,
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2021-04-01 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Lucas',
                'surname' => 'Dos Santos Silva',
                'salary' => 2000,
                'agreement' => 0,
                'contacts' => json_encode(['+5573988558247']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 2,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73988737066',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2022-01-10 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Paulo Henrique',
                'surname' => 'Freitas dos Santos',
                'salary' => 2824,
                'agreement' => 0,
                'contacts' => json_encode(['+5573988262401']),
                'function_name' => 'Caldeireiro',
                'transportation_voucher' => false,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73998425026',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2022-01-11 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Marcus Vinicius',
                'surname' => 'Lima Santos',
                'salary' => 2000,
                'agreement' => 0,
                'contacts' => json_encode(['+557388772557']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 2,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73988772557',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2022-07-12 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Rodrigo',
                'surname' => 'Marques Souza',
                'salary' => 2824,
                'agreement' => 0,
                'contacts' => json_encode(['+557388795619']),
                'function_name' => 'Caldeireiro',
                'transportation_voucher' => false,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73981830920',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2022-07-12 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Robson',
                'surname' => 'Pereira de Almeida',
                'salary' => 2000,
                'agreement' => 0,
                'contacts' => json_encode(['+5573981061797']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 4,
                'overtime_payment_method_id' => 4,
                'bank_id' => null,
                'pix_cpf' => '05274260594',
                'pix_email' => null,
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2022-11-03 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Ualas',
                'surname' => 'Quirino dos Santos',
                'salary' => 2824,
                'agreement' => 0,
                'contacts' => json_encode(['+5573988527460']),
                'function_name' => 'Caldeireiro',
                'transportation_voucher' => false,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73988527460',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2023-06-12 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Usiel',
                'surname' => 'Jesus dos Santos',
                'salary' => 2000,
                'agreement' => 0,
                'contacts' => json_encode(['+557398883272']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 3,
                'overtime_payment_method_id' => 3,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => 'usielsantos01@outlook.com',
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2023-10-23 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Arionaldo',
                'surname' => 'Filho Santos Silva',
                'salary' => 2000,
                'agreement' => 0,
                'contacts' => json_encode(['+5554984493119']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => true,
                'payment_method_id' => 4,
                'overtime_payment_method_id' => 4,
                'bank_id' => null,
                'pix_cpf' => '02353492592',
                'pix_email' => null,
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2023-12-11 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'João Victor',
                'surname' => 'Dos Santos Nery',
                'salary' => 1600,
                'agreement' => 0,
                'contacts' => json_encode(['+5573981698360']),
                'function_name' => 'Ajudante de Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73988651766',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2023-12-19 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Jadisson',
                'surname' => 'Santos Aragão',
                'salary' => 2000,
                'agreement' => 0,
                'contacts' => json_encode(['+557399140126']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 4,
                'overtime_payment_method_id' => 4,
                'bank_id' => null,
                'pix_cpf' => '03508201554',
                'pix_email' => null,
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2024-01-16 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Douglas',
                'surname' => 'Lima de Barros',
                'salary' => 1600,
                'agreement' => 0,
                'contacts' => json_encode(['+5573981537213']),
                'function_name' => 'Ajudante de Serralheiro',
                'transportation_voucher' => true,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73981537213',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2024-01-22 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'José Antônio',
                'surname' => 'Oliveira dos Santos',
                'salary' => 2000,
                'agreement' => 0,
                'contacts' => json_encode(['+5531994484841']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '31994484841',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2024-03-26 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Ademilton',
                'surname' => 'Amaral de Jesus',
                'salary' => 2500,
                'agreement' => 0,
                'contacts' => json_encode(['+557388759719']),
                'function_name' => 'Serralheiro',
                'transportation_voucher' => false,
                'payment_method_id' => 4,
                'overtime_payment_method_id' => 4,
                'bank_id' => null,
                'pix_cpf' => '03221379501',
                'pix_email' => null,
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2024-05-14 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Beatriz',
                'surname' => 'Cruz de Souza',
                'salary' => 1800,
                'agreement' => 0,
                'contacts' => json_encode(['+557399531517']),
                'function_name' => 'Aux de Escritório',
                'transportation_voucher' => true,
                'payment_method_id' => 4,
                'overtime_payment_method_id' => 4,
                'bank_id' => null,
                'pix_cpf' => '07754502518',
                'pix_email' => null,
                'pix_phone_number' => null,
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2024-06-10 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Davi',
                'surname' => 'Moreno Góes',
                'salary' => 1600,
                'agreement' => 0,
                'contacts' => json_encode(['+5573981823738']),
                'function_name' => 'Auxiliar de Almoxarifado',
                'transportation_voucher' => false,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73981823738',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2024-06-18 00:00:00',
                'updated_at' => $now
            ],
            [
                'name' => 'Danilo',
                'surname' => 'Sampaio dos Santos',
                'salary' => 1600,
                'agreement' => 0,
                'contacts' => json_encode(['+5573981539839']),
                'function_name' => 'Ajudante de Serralheiro',
                'transportation_voucher' => true,
                'payment_method_id' => 5,
                'overtime_payment_method_id' => 5,
                'bank_id' => null,
                'pix_cpf' => null,
                'pix_email' => null,
                'pix_phone_number' => '73981539839',
                'pix_token' => null,
                'bank_ag' => null,
                'account_type_id' => null,
                'account_number' => null,
                'fired' => false,
                'created_at' => '2024-06-25 00:00:00',
                'updated_at' => $now
            ],
        ]);
    }
}
